"use client"
import React, { useEffect, useState } from 'react'
import ReportForm from '../../components/ReportForm'
import supabase from '../../src/lib/supabaseClient'

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([])
  const [userMap, setUserMap] = useState<Record<string, { name: string | null; email: string }>>({})
  const [loading, setLoading] = useState(true)
  const [errorMessage, setErrorMessage] = useState('')

  useEffect(() => {
    let mounted = true
    ;(async () => {
      const { data: sessionData } = await supabase.auth.getSession()
      const accessToken = sessionData.session?.access_token
      const currentUserId = sessionData.session?.user?.id

      if (!currentUserId) {
        if (!mounted) return
        setReports([])
        setUserMap({})
        setLoading(false)
        return
      }

      let activeUsersById: Record<string, { name: string | null; email: string }> = {}
      if (accessToken) {
        const usersRes = await fetch('/api/users/active', {
          method: 'GET',
          headers: { Authorization: `Bearer ${accessToken}` }
        })
        const usersPayload = await usersRes.json().catch(() => ({}))
        if (usersRes.ok) {
          activeUsersById = (usersPayload.users || []).reduce((acc: Record<string, { name: string | null; email: string }>, item: any) => {
            acc[item.id] = { name: item.name || null, email: item.email }
            return acc
          }, {})
        }
      }

      const { data, error } = await supabase
        .from('reports')
        .select('id,filename,url,content_type,generated_at,generated_by,start_date,end_date,frequency')
        .eq('generated_by', currentUserId)
        .order('generated_at', { ascending: false })
        .limit(50)

      if (!mounted) return
      if (error) {
        setErrorMessage(error.message || 'Failed to load reports.')
        setReports([])
        setLoading(false)
        return
      }

      setReports(data || [])
      setUserMap(activeUsersById)
      setLoading(false)
    })()

    return () => { mounted = false }
  }, [])

  return (
    <section>
      <h1 className="text-2xl font-semibold mb-4">Reports</h1>
      <div className="mb-4">
        <p className="text-sm ucc-muted">Generate daily, weekly, or bi-weekly reports for everything, your tasks, a department, or a specific user.</p>
      </div>
      <div className="grid grid-cols-2 gap-6">
        <div>
          <ReportForm />
        </div>
        <aside className="ucc-card p-4">
          <h2 className="font-semibold mb-2">Recent Generated Reports</h2>
          {loading && <p className="text-sm ucc-muted">Loading reports...</p>}
          {!loading && errorMessage && <p className="text-sm text-red-700">{errorMessage}</p>}
          <ul className="text-sm space-y-2">
            {(reports || []).map((r: any) => (
              <li key={r.id} className="border-b pb-2">
                <div className="font-medium">{r.filename}</div>
                <div className="text-xs ucc-muted">{new Date(r.generated_at).toLocaleString()} • {r.frequency || '—'}</div>
                <div className="text-xs ucc-muted">
                  Generated by:{' '}
                  {r.generated_by
                    ? (userMap[r.generated_by]
                      ? `${userMap[r.generated_by].name || userMap[r.generated_by].email} (${userMap[r.generated_by].email})`
                      : 'Deactivated or unavailable user')
                    : 'Unknown'}
                </div>
                <div className="mt-1"><a className="ucc-link" href={r.url} target="_blank">Download</a></div>
              </li>
            ))}
            {(!reports || reports.length === 0) && <li className="ucc-muted">You have not generated any reports yet.</li>}
          </ul>
        </aside>
      </div>
    </section>
  )
}
